# Pytorch similar to Numpy

In [2]:
import torch

In [3]:
a = torch.tensor([1, 2, 3, 4])
print(a)
print(type(a))
print(a.dtype)
print(a.shape)
b = torch.tensor([1, 2, 3.1, 4])
print(b.dtype)

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.int64
torch.Size([4])
torch.float32


In [4]:
A = torch.tensor([[1, 2], [3, 4]])
# A = torch.tensor([[1, 2], [3, 4, 5]])
print(A)
print(A.shape)
print(A.ndim)
print(A.numel()) # if you want to get the same result of A.size of Numpy, you can use A.numel() instead!

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
2
4


In [5]:
print(torch.zeros(5))
print(torch.zeros_like(A))
print(torch.ones(5))
print(torch.zeros(3, 3))
print(torch.arange(3, 10, 2))
print(torch.arange(0, 1, 0.1))
print(torch.linspace(0, 1, 10)) # In Torch, endpoint in linspace is not available!

tensor([0., 0., 0., 0., 0.])
tensor([[0, 0],
        [0, 0]])
tensor([1., 1., 1., 1., 1.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([3, 5, 7, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [6]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
c = a + b
print(c)

tensor([5, 7, 9])


In [7]:
A = torch.tensor([[1, 2, 3], [1, 2, 3]])
B = torch.tensor([[4, 5, 6], [1, 1, 1]])
C = A+B
D = A-B
print(C)
print(D)
print()
print(A*B)
print(A/B)
print(B**2)

tensor([[5, 7, 9],
        [2, 3, 4]])
tensor([[-3, -3, -3],
        [ 0,  1,  2]])

tensor([[ 4, 10, 18],
        [ 1,  2,  3]])
tensor([[0.2500, 0.4000, 0.5000],
        [1.0000, 2.0000, 3.0000]])
tensor([[16, 25, 36],
        [ 1,  1,  1]])


In [8]:
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[1, 2], [3, 4]])
print(A*B)
print(A@B)

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 7, 10],
        [15, 22]])


In [9]:
a = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7])
print(a[7:])
print(a[:7])
print(a[:])

tensor(1)
tensor(2)
tensor(9)
tensor([2, 3, 4])
tensor(8)
tensor([8, 9])
tensor([1, 2, 3, 4, 5, 6, 7])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [10]:
A = torch.tensor([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
print(A[0])
print(A[-1])
print(A[1:])
print(A[:])
print(A[0][2])
print(A[0, 2])
B = [[1, 2, 3, 4], [5, 6, 7, 8]]
print(B)
print(B[0][2])
print(A[1,:])
print(A[1,0:3:2])
print(A[:,2])
print(A[:][2])

tensor([1, 2, 3])
tensor([7, 8, 9])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(3)
tensor(3)
[[1, 2, 3, 4], [5, 6, 7, 8]]
3
tensor([4, 5, 6])
tensor([4, 6])
tensor([3, 6, 9])
tensor([7, 8, 9])


In [11]:
A = torch.tensor([[[0,1,2,3],[4,5,6,7],[8,9,10,11]],
                  [[12,13,14,15],[16,17,18,19],[20,21,22,23]]])
print(A)
print(A.shape)
print(A[0,1,2])

a = torch.tensor([[[1,2,3,4]]])
print(a.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])
tensor(6)
torch.Size([1, 1, 4])


In [12]:
# boolean indexing
a = [1,2,3,4,5,3,3]
print(a==3) # False: it's because type of a is list and "3" is just str. list is not equal to str
A = torch.tensor([[1,2,3,4], [5,3,7,3]])
print(A == 3) # it works in Pytorch!
print(A[A==3])

A[A==3] = 100
print(A)

A = torch.tensor([[1,2],[3,4],[5,6],[7,8]])
B = [True, False, False, True]
print(A[B, :])

b = torch.tensor([1,2,3,4])
print(b[[True, True, False, False]]) # The version of inserting list into pytorch index of b

False
tensor([[False, False,  True, False],
        [False,  True, False,  True]])
tensor([3, 3, 3])
tensor([[  1,   2, 100,   4],
        [  5, 100,   7, 100]])
tensor([[1, 2],
        [7, 8]])
tensor([1, 2])


In [13]:
# tensor indexing
a = torch.tensor([1,2,3,4,5])
A = a[2]
print(A)
A = a[torch.tensor(2)]
print(A)
A = a[torch.tensor([2,3,4])]
print(A)
A = a[torch.tensor([[2,2,2],[3,3,3]])]
print(A)

a = torch.tensor([[1,2,3],[4,5,6]])
print(a[0])
A = a[torch.tensor([[0,1],[1,1]])]
print(A.shape)
print(A)

tensor(3)
tensor(3)
tensor([3, 4, 5])
tensor([[3, 3, 3],
        [4, 4, 4]])
tensor([1, 2, 3])
torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[4, 5, 6],
         [4, 5, 6]]])


In [14]:
A = torch.tensor([[1,2],[3,4],[5,6],[7,8]])
print(A)
print(A.shape)

# 1. A[row, column]
print(A[0, 1])
# 2. A[ tensor(bool)] => bool list should be same with shape of A
print(A[torch.tensor([[False, True],[False, False],[False,True],[True, False]])])
print(A[A==2])
# 3. A[which index does True occur, which index does True occur]
print(A[[True, False, False, False], [False, True]])
# 4. A[tensor] => how do you stack the index of your choice
print(A[torch.tensor([1,1,2,2,2])])

print(A[torch.tensor([[0, 1], [2, 3]])])
print(A[torch.tensor([[0, 1], [2, 3]])].shape)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
torch.Size([4, 2])
tensor(2)
tensor([2, 6, 7])
tensor([2])
tensor([2])
tensor([[3, 4],
        [3, 4],
        [5, 6],
        [5, 6],
        [5, 6]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])


In [15]:
# Don't need ".random"
A = torch.randn(3, 3) # randn => random number of normal distribution
B = torch.rand(3, 3) # rand => random number(0 to 1) of uniform. Only Get positive real number
print(A)
print(B)
print(A[:,0])
print(A[A[:,0]<0, :])

tensor([[ 0.4713,  1.0467,  0.7294],
        [-0.2842,  1.3509,  0.7317],
        [ 0.2197,  1.1927, -0.2353]])
tensor([[0.4622, 0.0936, 0.1350],
        [0.3249, 0.2760, 0.8589],
        [0.9934, 0.8472, 0.0057]])
tensor([ 0.4713, -0.2842,  0.2197])
tensor([[-0.2842,  1.3509,  0.7317]])


In [16]:
A = torch.randn(3,3)
print(A)
print(torch.abs(A))
print(torch.sqrt(torch.abs(A)))
print(torch.exp(torch.tensor(1))) # e^1
print(torch.log(torch.abs(A)))
print(torch.log(torch.exp(torch.tensor(1)))) # log_e(e^1)
print(torch.log10(torch.tensor(10)))
print(torch.log2(torch.tensor(2)))
print(torch.round(A))
print(torch.round(A, decimals=2)) # up to the second decimal place
print(torch.floor(A)) # round up
print(torch.ceil(A)) # round down

tensor([[ 0.2824,  0.0221, -1.2431],
        [-0.6493, -0.0385,  0.6030],
        [ 0.5917, -0.4490, -1.5300]])
tensor([[0.2824, 0.0221, 1.2431],
        [0.6493, 0.0385, 0.6030],
        [0.5917, 0.4490, 1.5300]])
tensor([[0.5314, 0.1487, 1.1149],
        [0.8058, 0.1962, 0.7765],
        [0.7692, 0.6701, 1.2369]])
tensor(2.7183)
tensor([[-1.2643, -3.8118,  0.2176],
        [-0.4319, -3.2568, -0.5058],
        [-0.5247, -0.8007,  0.4253]])
tensor(1.0000)
tensor(1.)
tensor(1.)
tensor([[ 0.,  0., -1.],
        [-1., -0.,  1.],
        [ 1., -0., -2.]])
tensor([[ 0.2800,  0.0200, -1.2400],
        [-0.6500, -0.0400,  0.6000],
        [ 0.5900, -0.4500, -1.5300]])
tensor([[ 0.,  0., -2.],
        [-1., -1.,  0.],
        [ 0., -1., -2.]])
tensor([[ 1.,  1., -1.],
        [-0., -0.,  1.],
        [ 1., -0., -1.]])


In [17]:
# torch.pi is originally float but if you try to calculate with torch.tensor() then it would be change tensor
print(torch.sin(torch.tensor(torch.pi/6)))
print(torch.cos(torch.tensor(torch.pi/3)))
print(torch.tan(torch.tensor(torch.pi/4)))
print(torch.tanh(torch.tensor(-10)))

type(torch.tensor(1)/6)

tensor(0.5000)
tensor(0.5000)
tensor(1.)
tensor(-1.)


torch.Tensor

In [18]:
torch.nan
print(torch.log(torch.tensor(-1)))
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4]))) # you can check if there has non-number
print(torch.isinf(torch.tensor([1,2,3,4,torch.inf])))

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


In [19]:
A=torch.randn(3,4)
print(A)
print(torch.max(A))
print(torch.max(A,dim=0)) # this function change into one dimension tensor
print(torch.max(A,dim=1))
print(torch.max(A,dim=0, keepdims=True)) # this function show the result without changing demension
print(torch.max(A,dim=1, keepdims=True))

print(torch.min(A))
print(torch.min(A,dim=0))
print(torch.min(A,dim=1))
print(torch.argmax(A))
print(torch.argmax(A,dim=0)) # argmax => you can get the index of highest number in Tensor!
print(torch.argmax(A,dim=1))

tensor([[-0.0896,  0.4660,  0.7510,  1.5004],
        [-1.8464, -0.2739,  0.4454,  1.0037],
        [ 0.1151,  0.0196,  0.3537,  0.3668]])
tensor(1.5004)
torch.return_types.max(
values=tensor([0.1151, 0.4660, 0.7510, 1.5004]),
indices=tensor([2, 0, 0, 0]))
torch.return_types.max(
values=tensor([1.5004, 1.0037, 0.3668]),
indices=tensor([3, 3, 3]))
torch.return_types.max(
values=tensor([[0.1151, 0.4660, 0.7510, 1.5004]]),
indices=tensor([[2, 0, 0, 0]]))
torch.return_types.max(
values=tensor([[1.5004],
        [1.0037],
        [0.3668]]),
indices=tensor([[3],
        [3],
        [3]]))
tensor(-1.8464)
torch.return_types.min(
values=tensor([-1.8464, -0.2739,  0.3537,  0.3668]),
indices=tensor([1, 1, 2, 2]))
torch.return_types.min(
values=tensor([-0.0896, -1.8464,  0.0196]),
indices=tensor([0, 0, 1]))
tensor(3)
tensor([2, 0, 0, 0])
tensor([3, 3, 3])


In [20]:
A = torch.randn(6,1)
print(A)
a_sorted = torch.sort(A, dim=0)
print(a_sorted)
# you can only get indices of sorted tensor
print(a_sorted[1])

a = torch.randn(6,1)
print(a)
print(a.sort(dim=0))
print(a.sort(dim=0, descending=True))

print('#'*100)
print(torch.max(a))
print(a.max())
print(torch.abs(a))
print(a.abs())

tensor([[ 0.8381],
        [ 0.5763],
        [ 0.4711],
        [ 0.4936],
        [-0.6666],
        [ 0.0524]])
torch.return_types.sort(
values=tensor([[-0.6666],
        [ 0.0524],
        [ 0.4711],
        [ 0.4936],
        [ 0.5763],
        [ 0.8381]]),
indices=tensor([[4],
        [5],
        [2],
        [3],
        [1],
        [0]]))
tensor([[4],
        [5],
        [2],
        [3],
        [1],
        [0]])
tensor([[-1.2937],
        [-0.6749],
        [-0.3170],
        [-0.8317],
        [ 1.4240],
        [ 0.5639]])
torch.return_types.sort(
values=tensor([[-1.2937],
        [-0.8317],
        [-0.6749],
        [-0.3170],
        [ 0.5639],
        [ 1.4240]]),
indices=tensor([[0],
        [3],
        [1],
        [2],
        [5],
        [4]]))
torch.return_types.sort(
values=tensor([[ 1.4240],
        [ 0.5639],
        [-0.3170],
        [-0.6749],
        [-0.8317],
        [-1.2937]]),
indices=tensor([[4],
        [5],
        [2],
        [1],
        [3]

In [21]:
A = torch.randn(3,4)
print(A)
print(torch.sum(A))
print(torch.sum(A, dim=1))
print(torch.sum(A, dim=1, keepdim=True))
print('=='*50)
print(torch.mean(A))
print(torch.mean(A, dim=1))
print(torch.mean(A, dim=1, keepdim=True))
print(torch.std(A))

tensor([[-0.0379,  0.4204,  0.9751,  1.2097],
        [ 0.4924, -2.5060,  0.9250, -0.8750],
        [ 0.6441, -0.2571,  1.3664, -0.3135]])
tensor(2.0436)
tensor([ 2.5674, -1.9636,  1.4398])
tensor([[ 2.5674],
        [-1.9636],
        [ 1.4398]])
tensor(0.1703)
tensor([ 0.6419, -0.4909,  0.3600])
tensor([[ 0.6419],
        [-0.4909],
        [ 0.3600]])
tensor(1.0802)


In [22]:
A = torch.randint(1,5,size=(24,)) # Generates random integers from 1 to 4 with the specified size of (12,)
print(A)
print(A.shape)

B = A.reshape(2,3,4)
print(B)
print(B.ndim)
print(B.sum())
print(B.sum(dim=0, keepdim=True))
print(B.sum(dim=1, keepdim=True))
print(B.sum(dim=2, keepdim=True))

tensor([2, 2, 4, 3, 3, 1, 1, 3, 1, 2, 4, 1, 1, 3, 1, 4, 1, 2, 1, 1, 2, 1, 4, 3])
torch.Size([24])
tensor([[[2, 2, 4, 3],
         [3, 1, 1, 3],
         [1, 2, 4, 1]],

        [[1, 3, 1, 4],
         [1, 2, 1, 1],
         [2, 1, 4, 3]]])
3
tensor(51)
tensor([[[3, 5, 5, 7],
         [4, 3, 2, 4],
         [3, 3, 8, 4]]])
tensor([[[6, 5, 9, 7]],

        [[4, 6, 6, 8]]])
tensor([[[11],
         [ 8],
         [ 8]],

        [[ 9],
         [ 5],
         [10]]])


In [23]:
a = torch.tensor([1,2,3])
b = torch.tensor([2,2,1])
print(torch.sum(a*b))
a = a.reshape(3,1)
b = b.reshape(3,1)
print(a.transpose(1,0)@b)
print(a.permute(1,0)@b) # it would be more useful in more than 3 dimensions and beyond
print(a.T@b)  # it would be more useful in less than 2 dimestions
print(a.t()@b)

A = torch.randn(4,3,6)
print(A.permute(0,2,1).shape)
print(A.transpose(0,2).shape) # transpose() only can change 2 indecies

tensor(9)
tensor([[9]])
tensor([[9]])
tensor([[9]])
tensor([[9]])
torch.Size([4, 6, 3])
torch.Size([6, 3, 4])


In [24]:
A = torch.arange(20)
print(A)
print(A.reshape(4,5).shape)
print(A.reshape(4,-1).shape)
print(A.reshape(2,5,-1).shape)
print(A.reshape(2,-1,5).shape)
print(A.reshape(1,-1).shape)  # row vector
print(A.reshape(-1,1).shape)  # column vector

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
torch.Size([4, 5])
torch.Size([4, 5])
torch.Size([2, 5, 2])
torch.Size([2, 2, 5])
torch.Size([1, 20])
torch.Size([20, 1])


In [25]:
x = torch.randn(2,3,4,5,6)
print(x[1,2,:,:,:].shape)  # x[1, 2, ...] is equaled to x[1, 2, :, :, :]
print(x[1,2,...].shape)
print(x[:,:,:,:,3].shape)
print(x[...,3].shape)
print(x[1,:,:,3,:].shape)
print(x[1,...,3,:].shape)

torch.Size([4, 5, 6])
torch.Size([4, 5, 6])
torch.Size([2, 3, 4, 5])
torch.Size([2, 3, 4, 5])
torch.Size([3, 4, 6])
torch.Size([3, 4, 6])


In [26]:
A = torch.ones((2,3,4))
B = torch.zeros((2,3,4))

C = torch.hstack([A,B]) # don't use this function
D = torch.vstack([A,B]) # don't use this function

E = torch.cat([A,B], dim=0)
F = torch.cat([A,B], dim=1)
G = torch.cat([A,B], dim=2)

print(A)
print(B)
print(C)
print(D)
print(E)
print(F)
print(G)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([

In [27]:
A = torch.randn(1,1,1,3,1,1,4,1)
print(A.shape)
print(A.squeeze().shape)

torch.Size([1, 1, 1, 3, 1, 1, 4, 1])
torch.Size([3, 4])


In [28]:
A = torch.randn(3,4)
print(A.unsqueeze(dim=0).shape)
print(A.unsqueeze(dim=1).shape)
print(A.unsqueeze(dim=2).shape)
print(A.reshape(1,3,4).shape)
print(A.reshape(3,1,4).shape)
print(A.reshape(3,4,1).shape)

torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])
torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])


In [29]:
A = torch.tensor([[1,2], [3,4]])
B = A              # It share A address. So if you change element of B tensor, then the element of tensor of A is changed as well!
C = B.clone()      # you can use this function not to share the tensor address that you try to copy!
B[0,0] = 100

print(B)
print(A)
print(C)

tensor([[100,   2],
        [  3,   4]])
tensor([[100,   2],
        [  3,   4]])
tensor([[1, 2],
        [3, 4]])


## Let's find out about the "@"

In [30]:
A = torch.randn(5,7)
B = torch.randn(7,10)
C = A@B
print(C.shape)

A = torch.randn(32,5,7)
B = torch.randn(32,7,10)
C = A@B                  # if it's 3 dimension, it is calculated by dimension-wise inner product
print(C.shape)

torch.Size([5, 10])
torch.Size([32, 5, 10])


In [31]:
A = torch.randn(32,5,7)
B = torch.randn(7,10)

print((A@B).shape)
print(B.repeat(32,1,1).shape)
print((A@B.repeat(32,1,1)).shape)

a = torch.randn(3,4)
print(a.repeat(3,1,2,3).shape)

torch.Size([32, 5, 10])
torch.Size([32, 7, 10])
torch.Size([32, 5, 10])
torch.Size([3, 1, 6, 12])


In [32]:
import numpy as np
a = np.array([1,2,3])
b = torch.tensor([1,2,3])
A = torch.tensor(a)
print(type(A))
B = b.numpy()
print(type(B))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


# Autograd that made deep learning

In [33]:
x = torch.tensor([1.], requires_grad=True) # Must be float
print(x)

tensor([1.], requires_grad=True)


In [34]:
x = torch.tensor([1.])
print(x)
print(x.requires_grad)
x.requires_grad = True
print(x)
print(x.requires_grad)

tensor([1.])
False
tensor([1.], requires_grad=True)
True


In [35]:
x = torch.tensor([1.], requires_grad=True)
y = x**2
print(y)

y.backward()
print(x.grad)

tensor([1.], grad_fn=<PowBackward0>)
tensor([2.])


In [36]:
x = torch.tensor([1.], requires_grad=True)
y = x**2
print(y)
y.retain_grad()       # If you want to get the grad of mid tensor such as y, you can use it

z = 3*y
print(z)

z.backward()
print(x.grad)         # It figures out this grad by using chain rule
print(y.grad)         # By using .retain_grad() function, now you can get the y grad

tensor([1.], grad_fn=<PowBackward0>)
tensor([3.], grad_fn=<MulBackward0>)
tensor([6.])
tensor([3.])


In [37]:
x=torch.tensor([1.], requires_grad=True)
a = x**2
b = a+1
print(b)
c=b**2
c.backward()
print(x.grad)

tensor([2.], grad_fn=<AddBackward0>)
tensor([8.])


In [38]:
x = torch.tensor([1.], requires_grad=True)
y = torch.tensor([1.], requires_grad=True)
z = 2*x**2 + y**2
z.backward()
print(x.grad)
print(y.grad)

tensor([4.])
tensor([2.])


In [39]:
x = torch.tensor([1., 2., 3.], requires_grad=True)
y = torch.sum(x**2)             # that means x1**2 + x2**2 + x3**2
y.backward()
print(y)
print(x.grad)

tensor(14., grad_fn=<SumBackward0>)
tensor([2., 4., 6.])


In [40]:
x = torch.tensor([1.], requires_grad=True)
x.requires_grad = False

y = x**2
print(y)
# y.backward()     error!

tensor([1.])


In [41]:
x = torch.tensor([2.], requires_grad=True)
x = x.detach()
print(x)
y = x**2
print(y)

tensor([2.])
tensor([4.])


In [42]:
# detach and torch.no_grad
x = torch.tensor([1.], requires_grad=True)
# if you don't want to calculate the grad_fn temporary, you can use torch.no_grad()
# because you don't need to use Memerory when you test a model!
with torch.no_grad():
    y = x**2
    print(x.requires_grad)
    print(y)
print(x.requires_grad)
# y.backward() would be error at this line!!
y = x**2
print(y)       # now it works becuase the y = x**2 is out of the "with torch.no_grad()"" function

True
tensor([1.])
True
tensor([1.], grad_fn=<PowBackward0>)


In [48]:
x = torch.tensor([-1.], requires_grad=True)
y = torch.abs(x)

print(y)
y.backward()
print(x.grad)

tensor([1.], grad_fn=<AbsBackward0>)
tensor([-1.])
