# Make Simple Neural Network

In [1]:
import torch
from torch import nn

In [19]:
x = torch.tensor([1.])
model = nn.Linear(1,1)   # 1 linear unit with input node 1, output node 1

# Initialize weight, bias of model as you create it
print(model.weight)
print(model.bias)

y = model(x)
print(y)
print('=='*30)
y = x @ model.weight + model.bias
print(y)

Parameter containing:
tensor([[-0.7029]], requires_grad=True)
Parameter containing:
tensor([-0.3070], requires_grad=True)
tensor([-1.0099], grad_fn=<AddBackward0>)
tensor([-1.0099], grad_fn=<AddBackward0>)


In [30]:
# fully connected layer
fc1 = nn.Linear(1,3)
fc2 = nn.Linear(3,1)

print(fc1.weight)
print(fc1.bias)
print(fc2.weight)
print(fc2.bias)
print('=='*30)
x = torch.tensor([1.])
x = fc1(x)
print(x)
x = fc2(x)
print(x)
print('=='*30)
x = torch.tensor([1.])
print((x@fc1.weight.T + fc1.bias)@fc2.weight.T + fc2.bias)

Parameter containing:
tensor([[-0.8834],
        [ 0.7991],
        [-0.6759]], requires_grad=True)
Parameter containing:
tensor([0.9296, 0.7428, 0.4460], requires_grad=True)
Parameter containing:
tensor([[ 0.1581,  0.0042, -0.3152]], requires_grad=True)
Parameter containing:
tensor([0.1063], requires_grad=True)
tensor([ 0.0463,  1.5420, -0.2298], grad_fn=<AddBackward0>)
tensor([0.1926], grad_fn=<AddBackward0>)
tensor([0.1926], grad_fn=<AddBackward0>)


## Why doesn't nn.Linear() automatically transpose its shape from the start, but instead transpose inside the function and then proceeds with inner product?
 -  https://pytorch.org/docs/stable/generated/torch.nn.Linear.html
### nn.Linear() function want to get the data form (1D data) of "channel" in "number"x"channel"x"row"x"column"
### Node 1 is equal to 1 channel
### If you want a lot of data to pass through, you have to give it in the form of the number x channel
### why .T? it's because they also want to make weight like numberxchannel form
### First of all, "channel" in the weight shape in "number"x"channel" must match the number of pre-channel
### for example, nn.Linear(2,3) means The number of channels in front of the weights is 2, so if you convert it to number x channel format, it is ?x2. And we make 3 number of nodes by using 2 nodes. So it become 3(number)x2(channel).